#!/usr/bin/env bash

source "/Users/dongpham/Desktop/boilerplates/lib/bash/core.sh"

function main() {

  echo -e "${OK_COLOR}==> Initializing boilerplate..."

  "/Users/dongpham/Desktop/boilerplates//pipeline/boilerplate-upgrade"

  (
    set -x
    git add --all
    git commit --message "Setup project"
  )

}

main "$@"
