go get -u -v firebase.google.com/go                   
go get -u -v github.com/OneOfOne/xxhash               
go get -u -v github.com/aws/aws-sdk-go/aws            
go get -u -v github.com/aws/aws-sdk-go/aws/session    
go get -u -v github.com/aws/aws-sdk-go/service/sqs    
go get -u -v github.com/go-redis/redis                
go get -u -v github.com/go-sql-driver/mysql           
go get -u -v golang.org/x/oauth2/google               
go get -u -v google.golang.org/api/option             
go get -u -v gopkg.in/mgo.v2